### PR TITLE
Benchmarks

### PR DESCRIPTION
**Pull request by fosskers**
This is the first wave of benchmarks for this library. The idea is only to produce the benchmarks themselves - not try to interpret the results or fix any problems. That's for a PR that will follow this one.

### TODO
- [x] Get good geotiff
- [x] Benchmarks
  - [x] Raster Generation
  - [x] IO
  - [x] Colouring
  - [x] Local Ops
  - [x] Focal Ops
  - [x] Composite Ops (several Locals + Focals together)

Ping @lehins

### CODE REVIEW

**Comment by fosskers** [comment]
```
benchmarking Raster Creation/constant 256x256
time                 88.76 μs   (87.21 μs .. 90.59 μs)

benchmarking Raster Creation/constant 512x512
time                 251.4 μs   (237.3 μs .. 272.5 μs)

benchmarking Raster Creation/fromFunction 256x256
time                 515.5 μs   (501.4 μs .. 532.6 μs)

benchmarking Raster Creation/fromFunction 512x512
time                 2.100 ms   (2.048 ms .. 2.155 ms)

benchmarking Raster Creation/fromVector Unboxed Int - 256x256
time                 170.2 ns   (169.6 ns .. 170.9 ns)

benchmarking Raster Creation/fromVector Boxed Int - 256x256
time                 90.75 μs   (89.73 μs .. 91.94 μs)
```
Nice instantaneous creation from unboxed vectors.

**Comment by fosskers** [comment]
```
benchmarking IO/fromRGBA 512x512
time                 17.00 ms   (16.27 ms .. 17.50 ms)
             
benchmarking IO/fromRGBA (Word8 -> Double) 512x512
time                 83.87 ms   (79.84 ms .. 87.45 ms)

benchmarking IO/fromGray Multiband 512x512
time                 149.5 ms   (145.4 ms .. 151.8 ms)
             
benchmarking IO/fromGray Singleband 512x512
time                 2.380 ms   (2.350 ms .. 2.397 ms)
```
`fromGray` here is reading an RGBA image and presumably crushing all the bands together.

**Comment by fosskers** [comment]
```
benchmarking Colouring/classify 512x512
time                 4.053 ms   (3.940 ms .. 4.135 ms)
             
benchmarking Colouring/grayscale 512x512
time                 1.008 ms   (987.2 μs .. 1.035 ms)
```

**Comment by fosskers** [comment]
```
benchmarking Local Operations/fmap (+ 17) . lazy
time                 1.022 ms   (986.4 μs .. 1.061 ms)
             
benchmarking Local Operations/zipWith (+)
time                 17.35 ms   (16.71 ms .. 17.93 ms)

benchmarking Local Operations/zipWith (/)
time                 2.179 ms   (2.078 ms .. 2.253 ms)
             
benchmarking Local Operations/(+)
time                 17.06 ms   (16.24 ms .. 17.48 ms)

benchmarking Local Operations/(/)
time                 3.307 ms   (3.200 ms .. 3.394 ms)
  
benchmarking Local Operations/lmax
time                 5.693 ms   (5.511 ms .. 5.863 ms)
             
benchmarking Local Operations/lmin
time                 5.417 ms   (5.189 ms .. 5.608 ms)
             
benchmarking Local Operations/lmean
time                 47.20 ms   (44.69 ms .. 48.69 ms)
             
benchmarking Local Operations/lvariety
time                 43.38 ms   (41.27 ms .. 44.51 ms)
             
benchmarking Local Operations/lmajority
time                 51.97 ms   (48.85 ms .. 53.50 ms)
             
benchmarking Local Operations/lminority
time                 52.06 ms   (49.70 ms .. 53.29 ms)
             
benchmarking Local Operations/lvariance
time                 84.42 ms   (80.50 ms .. 86.86 ms)
```

Zzz.... so slow. A lot of `NonEmpty` operations happening there.

**Comment by fosskers** [comment]
```
benchmarking Focal Operations/fsum
time                 35.69 ms   (33.61 ms .. 36.75 ms)
             
benchmarking Focal Operations/fmean
time                 47.32 ms   (44.84 ms .. 48.47 ms)
             
benchmarking Focal Operations/fmax
time                 50.84 ms   (48.45 ms .. 52.27 ms)
             
benchmarking Focal Operations/fmin
time                 51.08 ms   (47.72 ms .. 53.50 ms)
             
benchmarking Focal Operations/fmajority
time                 125.4 ms   (118.4 ms .. 129.7 ms)
             
benchmarking Focal Operations/fminority
time                 126.0 ms   (119.0 ms .. 130.8 ms)
             
benchmarking Focal Operations/fvariety
time                 75.39 ms   (70.09 ms .. 77.46 ms)
             
benchmarking Focal Operations/fpercentage
time                 42.46 ms   (40.38 ms .. 43.58 ms)
             
benchmarking Focal Operations/fpercentile
time                 47.56 ms   (42.57 ms .. 57.83 ms)
             
benchmarking Focal Operations/flinkage
time                 97.53 ms   (92.63 ms .. 101.3 ms)
             
benchmarking Focal Operations/flength
time                 222.4 ms   (212.3 ms .. 229.8 ms)
             
benchmarking Focal Operations/fpartition
time                 82.29 ms   (78.65 ms .. 84.54 ms)
             
benchmarking Focal Operations/fshape
time                 114.1 ms   (107.6 ms .. 117.2 ms)
             
benchmarking Focal Operations/ffrontage
time                 166.7 ms   (155.4 ms .. 180.2 ms)
             
benchmarking Focal Operations/farea
time                 171.3 ms   (163.4 ms .. 180.8 ms)
             
benchmarking Focal Operations/fvolume
time                 248.8 ms   (227.7 ms .. 263.2 ms)
             
benchmarking Focal Operations/fgradient
time                 436.1 ms   (430.7 ms .. 442.1 ms)
             
benchmarking Focal Operations/faspect/Unsafe
time                 477.3 ms   (469.9 ms .. 484.0 ms)
             
benchmarking Focal Operations/faspect/Safe
time                 573.0 ms   (559.1 ms .. 587.1 ms)
             
benchmarking Focal Operations/fdownstream/Word
time                 293.2 ms   (249.1 ms .. 413.1 ms)
             
benchmarking Focal Operations/fupstream/Word
time                 293.0 ms   (274.1 ms .. 305.0 ms)
```
These look slow, but nothing is inlined yet. I know for a fact that `fsum` drops from 36ms to 1ms *just* by inlining, so I'm hopeful for the others.

**Comment by lehins** [comment]
Thought about running your benchmarks on my machine, but the test images are missing from the repo `512x512.tif`

**Comment by fosskers** [comment]
Yeah, I haven't committed them yet. I can do that in an hour or so.

**Comment by fosskers** [comment]
Pushed! Go nuts.

**Comment by fosskers** [comment]
```
benchmarking Numeric Conversion/realToFrac on Raster
time                 11.00 ms   (10.52 ms .. 11.47 ms)
```
Converting a 512x512 Raster from `Word8` to `Double` (and forcing memory).

**Comment by fosskers** [comment]
```
benchmarking Massiv Operations/strict S . lazy
time                 999.6 μs   (971.7 μs .. 1.026 ms)
             
benchmarking Massiv Operations/strict U . lazy
time                 1.004 ms   (987.2 μs .. 1.019 ms)
             
benchmarking Massiv Operations/strict P . lazy
time                 1.001 ms   (983.2 μs .. 1.016 ms)
```
Converting to `D` then reforcing memory. This is probably a lower bound, since `lazy` is already INLINEd and it's just a wrapper around `delay`.

**Comment by fosskers** [comment]
```
benchmarking Composite Operations/NDVI
time                 20.80 ms   (19.82 ms .. 21.46 ms)
```
This I'm pretty happy about.

**Comment by fosskers** [comment]
I realize it might be a mistake to have `RGBARaster` defined with `D`s like so:
```haskell
data RGBARaster p r c a = RGBARaster { _red   :: Raster D p r c a
                                     , _green :: Raster D p r c a
                                     , _blue  :: Raster D p r c a
                                     , _alpha :: Raster D p r c a }
```
Any repeated calls to say, the `_red` field will repeat all the work that created that `D` - namely mapping through the entire original `S` Array to grab only a certain portion of the `PixelRGBA`.

I thought having them as `D` would be an advantage, since unused bands wouldn't waste time being mapped... but now there's this other pitfall. Not sure what to do.

**Comment by lehins** [comment]
@fosskers, that's right decision to to keep `RGBARaster` as `S`, this way you can avoid mapping multiple times. I'd suggest making the fields themselves strict too, i.e. `_red :: !(Raster S p r c a)`. Here is the only way you can avoid mapping multiple times, is to use mutation. There are two options `imapM_` for sequential mapping and `imapP_` for parallel, here is the latter:

```haskell
fromRGBA :: forall p r c a. (Elevator a, KnownNat r, KnownNat c) => FilePath -> IO (Either String (RGBARaster p r c a))
fromRGBA fp = do
  cap <- getNumCapabilities
  img <- setComp (bool Par Seq $ cap == 1) <$> readImageAuto fp
  let rows = fromInteger $ natVal (Proxy :: Proxy r)
      cols = fromInteger $ natVal (Proxy :: Proxy c)
      (r :. c) = size img
  if r == rows && c == cols
    then do
    (ar, ag, ab, aa) <- spreadRGBA img
    return $ Right $ RGBARaster (Raster ar) (Raster ag) (Raster ab) (Raster aa)
    else return $ (Left $ printf "Expected Size: %d x %d - Actual Size: %d x %d" rows cols r c)
{-# INLINE fromRGBA #-}

spreadRGBA ::
     (Index ix, Elevator e)
  => A.Array S ix (Pixel RGBA e)
  -> IO (A.Array S ix e, A.Array S ix e, A.Array S ix e, A.Array S ix e)
spreadRGBA arr = do
  let sz = A.size arr
  mr <- A.unsafeNew sz
  mb <- A.unsafeNew sz
  mg <- A.unsafeNew sz
  ma <- A.unsafeNew sz
  flip A.imapP_ arr $ \ ix (PixelRGBA r g b a) -> do
    A.unsafeWrite mr ix r
    A.unsafeWrite mg ix g
    A.unsafeWrite mb ix b
    A.unsafeWrite ma ix a
  ar <- A.unsafeFreeze (getComp arr) mr
  ag <- A.unsafeFreeze (getComp arr) mg
  ab <- A.unsafeFreeze (getComp arr) mb
  aa <- A.unsafeFreeze (getComp arr) ma
  return (ar, ag, ab, aa)
{-# INLINE spreadRGBA #-}
```

**Comment by fosskers** [comment]
Oh awesome, thank you. I'll use that in my next PR which involves actually trying to improve performance.

**Comment by fosskers** [comment]
```
benchmarking Composite Operations/NDVI
time                 16.04 ms   (15.40 ms .. 16.50 ms)
             
benchmarking Composite Operations/EVI
time                 47.96 ms   (44.05 ms .. 50.92 ms)
```
Also elegant:
```haskell
-- | See: https://en.wikipedia.org/wiki/Normalized_difference_vegetation_index
ndvi :: Raster D p 512 512 Double -> Raster D p 512 512 Double -> Raster D p 512 512 Double
ndvi nir red = (nir - red) / (nir + red)

-- | See: https://en.wikipedia.org/wiki/Enhanced_vegetation_index
evi :: RGBARaster p 512 512 Double -> Raster D p 512 512 Double
evi (RGBARaster r g b _) = 2.5 * (numer / denom)
  where nir   = g  -- fudging it.
        numer = nir - r
        denom = nir + (6 * r) - (7.5 * b) + 1
```
Constants can be used to represent Rasters of only that value :)

**Pull request merged**
